// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopHeroesBot.Infrastructure.Data;

#nullable disable

namespace TopHeroesBot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804154734_AddGiftCode")]
    partial class AddGiftCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TopHeroesBot.Domain.Entities.Account", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TopHeroesBot.Domain.Entities.DailyHistory", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Uid", "Date");

                    b.ToTable("DailyHistories");
                });

            modelBuilder.Entity("TopHeroesBot.Domain.Entities.GiftCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("GiftCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
